### ISSUE TITLE
Redirect all HTTP requests to HTTPS

### ISSUE THREAD

**Issue by 0xMurage** [tunapanda/wikonnect_landing#8]
The server should always serve a secure version of the site. This could increase site visitor's trust towards the site.
#### Expected Behavior
All insecure site requests should automatically redirect to secure  URI
#### Current Behavior
Users who visit the site through www.wikonnect.org or http://wikonnect.org are not automatically redirected to the secure URI

**Comment by mrlarso** [comment]
This has been solved
